### ISSUE TITLE
[Bug] Combination registerAdjuster="afterTax" and includeShipping="false"

### ISSUE THREAD

**Issue by sander-lameco** [verbb/gift-voucher#148]
### Describe the bug

When having the following configuration set:

```
'registerAdjuster' => 'afterTax',
'includeShipping' => false,
```

The Voucher Code will not take the `tax` value into account and only applies the same amount as the subtotal of items.

When I remove the `'includeShipping' => false` line the Voucher Code will take the `tax amount into account.

Screenshots:

**With includeShipping => false**

<img width="367" height="185" alt="Image" src="https://github.com/user-attachments/assets/43366e7b-23ee-4340-aa56-df995a82a85a" />

**Without includeShipping => false**

<img width="352" height="174" alt="Image" src="https://github.com/user-attachments/assets/df2ad718-88ff-4517-b963-ada722b027ba" />

In our clients case this is an issue, since they don't want the shipping to be included but want the tax to be.

### Steps to reproduce

1. Apply the provided config
2. Add a tax rule
3. Add a shipping rule
4. Add a product to the cart
5. Apply the voucher

### Craft CMS version

4.16.15

### Plugin version

3.0.20

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/gift-voucher:"dev-craft-4 as 3.0.20"`.

**Comment by sander-lameco** [comment]
@engram-design so I did some testing after running the `composer require` command, but for some reason the outcome is still the same.

Somehow it's locking it to a commit prior to your latest commit with the fix:

<img width="854" height="139" alt="Image" src="https://github.com/user-attachments/assets/7540d92b-012f-451c-85a2-9c42bd89f749" />

I tried forcing the latest commit by using without any luck:
```
rm -rf vendor/verbb/gift-voucher && composer clear-cache && composer update verbb/gift-voucher
```

If I do the same change you've done in your latest commit https://github.com/verbb/gift-voucher/commit/dce993f8de8bbd59d497070ff7f0bf9386c603f4 at least I can confirm it works.

Do you have an ETA on the next release?

**Comment by engram-design** [comment]
Huh, that’s a little odd. Anyway, will have a release out end of the week!

**Comment by sander-lameco** [comment]
Yea not sure whats happening there with composer. Thought it might have been cache.
Thanks anyway!

**Comment by Stan-S-99** [comment]
Hi @engram-design,

Could it be that the release is not out yet? 
Happy to hear from you!

**Comment by Stan-S-99** [comment]
Hi, 

Could you share an updated ETA for the fix? We are currently experiencing issues in the checkout process because of this.

**Comment by sander-lameco** [comment]
Hi @engram-design hope you had good holidays and I which you a happy new year.

I was wondering when the release will be available so we can close this issue and the issue with our client.

**Comment by engram-design** [comment]
Not fully back on board until next week, but will be tagging a release within the next 7 days.

**Comment by Stan-S-99** [comment]
Hi,

Is there anything you could do to have this live sooner? Right now alot of customers are calling because of this issue with the vouchers because the payment info is not correct

**Comment by engram-design** [comment]
You can get the dev version early via `composer require verbb/gift-voucher:"dev-craft-4 as 3.0.20"`.

**Comment by engram-design** [comment]
Updated in [3.0.21](https://github.com/verbb/gift-voucher/releases/tag/3.0.21).

**Comment by sander-lameco** [comment]
Thanks, just tested and works as intended!
